name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta automáticamente al hacer push a main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos a Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Si tus archivos están en /docs cambia esto a 'docs'

      - name: Desplegar en Pages
        uses: actions/deploy-pages@v4
